#!/usr/bin/env bash

# ---------------------------------------------------------------------
# 
# Copyright (C) 2026 @Sebastian Kinnewig
#
# This file is part of the Kanka CE toolchain.
# It is NOT part of the official Kanka project and is not affiliated
# with or endorsed by the Kanka developers.
#
# The code in this file is licensed under the GNU Lesser General
# Public License v2.1 (LGPL-2.1) as published by the Free Software
# Foundation.
#
# The full text of the license can be found in the file LICENSE.md.
#
# ---------------------------------------------------------------------

# ++============================================================++
# ||                         Premilaris                         ||
# ++============================================================++
set -e

# Colours for progress and error reporting
ERROR="\033[1;31m"
GOOD="\033[1;32m"
WARN="\033[1;35m"
INFO="\033[1;34m"
BOLD="\033[1m"

# Display messages in a specified colour
cecho() {
  COL=$1; shift
  echo -e "${COL}$@\033[0m"
}

# Error codes
E_OK=0
E_USAGE=1
E_UPSTREAM_NOT_FOUND=2
E_OUTPUT_WRITE_FAIL=3
E_PATCH_FAILED=4
E_RESOURCE_FAILED=5
E_STEP_FAILED=6
E_DEPENDENCY_MISSING=7

# Error handling
error() {
    local message="$1"
    local code="${2:-1}"

    cecho ${ERROR} "ERROR: $message" >&2
    exit "$code"
}

# Tools directory
TOOLS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"



# ++============================================================++
# ||                       Parse arguments                      ||
# ++============================================================++
parse_arguments() {
  # Parse command line arguments
  while [[ $# -gt 0 ]]; do
    KEY="$1"
    case $KEY in
      # Help
      -h|--help)
        echo "Kanka CE Tools, Version $(cat VERSION)"
        echo "Usage: $0 [options] --kanka-dir=</Path/to/kanka>"
        echo "  -h,           --help      Print this message"
        echo "  -p (required) --kanka-dir Path to kanka directory"
        echo "  -i            --icons     Select which icon set to use, options <fontawesome-free|fontawesome-nonfree|lineawesome>, defaults to fontawesome-free"
        exit 0
      ;;

      # KANKA ROOT DIRECTORY
      -p|--kanka-dir)
        KANKA_ROOT_DIR="$2"
        shift
        shift
        ;;

      # ICON SET
      -i|--icons)
        ICONS="$2"
        shift
        shift
        ;;
        
      # unknown flag
      *)
        error "Invalid command line option <$KEY>. See -h for more information." $E_USAGE
        ;;
    esac
  done

  # --- KANKA ROOT DIRECTORY ---
  # If user provided path is not set, break
  cecho ${INFO} "Kanka root directory:"
  if [ -z "${KANKA_ROOT_DIR}" ]; then
    cecho ${INFO} "  You have to provide the path where the Kanka root directory is located"
    cecho ${INFO} "  via the -p <DIR> or --kanka_dir <DIR> option."
    error "Kanka root directory was not provide" $E_USAGE
  else 
    # Check the input argument of the install path and replace the tilde
    # character '~' by the users home directory ${HOME}. 
    KANKA_ROOT_DIR=${KANKA_ROOT_DIR/#~\//$HOME\/}
    echo "  ${KANKA_ROOT_DIR}"
  fi

  # --- ICON SET ---
  # If user provided icons is not set, use default 
  cecho ${INFO} "Icons to use:"
  if [ -z "${ICONS}" ]; then
    ICONS="fontawesome-free"
    cecho ${INFO} "  No icon-set selected, default to fontawesome-free."
    cecho ${INFO} "  To use different icons use the -i <ICONS-NAME> or --icons <ICONS-NAME> option."
    cecho ${INFO} "  The available ooptions are: fontawesome-free, fontawesome-nonfree and lineawesome."
  fi
}


# ++============================================================++
# ||                    The actual program                      ||
# ++============================================================++

# --- Verify that the script is called from the kanka root directory ---
if [ "$(pwd)" != "${TOOLS_ROOT}" ]; then
  error "This script has to be called from the kanka-ce-tools root directory." $E_USAGE
fi


# -- Parse arguments ---
if ! parse_arguments "$@"; then
  exit 0
fi


# --- Apply Patches ---
cecho ${INFO} "Replace Icons"
if ! bash "$TOOLS_ROOT/patches/icons/replace-fontawesome.sh" "$TOOLS_ROOT" "$KANKA_ROOT_DIR" "$ICONS" "$@"; then
  error "Icon replacement failed" 2
fi
cecho ${GOOD} "Done!"

cecho ${INFO} "Apply patches"
if ! bash 
for file in $TOOLS_ROOT/patches/patch-files/*.patch; do
    echo "  Apply: $file"
    patch -p1 -d $KANKA_ROOT_DIR < "$file" || {
        error "Patch $file failed" 2
    }
done
cecho ${GOOD} "Done!"

echo
cecho ${GOOD} "All Done!"
