name: Build and Release Container

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ce-release-published]
    
permissions: write-all

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build script
        run: |
          ./build-container.sh

      - name: Repository owner 
        run: echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Tag image for GHCR
        run: |
          # version number
          podman tag kanka-ce:latest \
            ghcr.io/${{ env.OWNER }}/kanka-ce:${{ github.event.client_payload.version }}

          # latest
            podman tag kanka-ce:latest \
              ghcr.io/${{ env.OWNER }}/kanka-ce:latest

      - name: Push image
        run: |
          # version number
          podman push ghcr.io/${{ env.OWNER }}/kanka-ce:${{ github.event.client_payload.version }}

          # latest
          podman push ghcr.io/${{ env.OWNER }}/kanka-ce:latest
